#配置rabbitmq
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost

  application:
    name: springboot-rabbitmq

server:
  port: 10086