#配置rabbitmq
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost

    # 消费端可靠性之发布者确认类型
    #publisher-confirm-type: correlated
    # 消费端可靠性之发布者是否返回
    #publisher-returns: true

    # 监听消费者消息是否确认 auto：自动确认,manual:手动 none：拒接接收
    listener:
      simple:
        # 监听消费者消息是否确认 auto：自动确认,manual:手动 none：拒接接收
        acknowledge-mode: auto
        #acknowledge-mode: manual 手动
        #acknowledge-mode: none 拒绝
        #acknowledge-mode: auto 自动


  application:
    name: springboot-rabbitmq

server:
  port: 10086