#配置rabbitmq
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost

    # 消费端可靠性之发布者确认类型
    #publisher-confirm-type: correlated
    # 消费端可靠性之发布者是否返回
    #publisher-returns: true


  application:
    name: springboot-rabbitmq

server:
  port: 10086