# yml、yaml、properties的优先级是从低到高

server:
  port: 8081
  # 当value值为普通数据类型（例如数字、字符串、布尔等）不需要额外添加引号
  servlet:
    context-path: /test
spring:
  application:
    name: springBootBasic
# person类的自定义使用
person:
  id: 2
  name: 李四
  # 当value值为数组和单列集合，两种写法：缩进式写法和行内写法
  # 缩进式写法
  hobby:
    - 吃饭
    - 打游戏
    - 打豆豆
  # 行内写法
  like:
    play,
    read,
    sleep
  family: [ father,monther,son ]
  map:
    key1: key1
    key2: key2
  pet:
    type: cat
    name: Mickey
