server:
  port: 18081

spring:
  application:
    name: redis

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 20
        min-idle: 2
    timeout: 5000
    password: 123456